apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  labels:
    app: kafka
spec:
  ports:
    - port: 29092
      name: server
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka1
spec:
  selector:
    pod-name: kafka1
  ports:
    - port: 9093
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka1-ext
# spec:
#   selector:
#     pod-name: kafka1
#   ports:
#     - port: 9092
#       nodePort: 30008
#   type: NodePort
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka1
spec:
  selector:
    matchLabels:
      pod-name: kafka1
  template:
    metadata:
      labels:
        app: kafka
        pod-name: kafka1
    spec:
      containers:
        - name: kafka1
          image: wurstmeister/kafka
          ports:
            - containerPort: 9093
            - containerPort: 29092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181/kafka
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:29092,PLAINTEXT_HOST://0.0.0.0:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://:29092,PLAINTEXT_HOST://kafka1:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
