apiVersion: v1
kind: Service
metadata:
    name: kafka1
spec:
    selector:
        app: kafka
    ports:
        - port: 9092
          name: kafka-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kafka
spec:
    selector:
        matchLabels:
            app: kafka
    replicas: 1
    template:
        metadata:
            labels:
                app: kafka
        spec:
            containers:
                - name: kafka
                  image: wurstmeister/kafka
                  ports:
                      - containerPort: 9092
                  env:
                      - name: KAFKA_ZOOKEEPER_CONNECT
                        value: zookeeper:2181/kafka
                      - name: KAFKA_BROKER_ID
                        value: "0"
                      - name: KAFKA_LISTENERS
                        value: PLAINTEXT://:9092
                      - name: KAFKA_ADVERTISED_HOST_NAME
                        value: kafka1
