apiVersion: v1
kind: Service
metadata:
  name: kafka2
spec:
  selector:
    pod-name: kafka2
  ports:
    - port: 9093
      name: ext
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka2
spec:
  selector:
    matchLabels:
      pod-name: kafka2
  template:
    metadata:
      labels:
        pod-name: kafka2
        app: kafka
    spec:
      hostname: kafka2
      containers:
        - name: kafka2
          image: wurstmeister/kafka
          ports:
            - containerPort: 9093
            - containerPort: 29092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181/kafka
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka2:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
