apiVersion: v1
kind: Service
metadata:
    name: kafka2
spec:
    selector:
        app: kafka2
    ports:
        - port: 9093
          name: kafka2
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kafka2
spec:
    selector:
        matchLabels:
            app: kafka2
    replicas: 1
    template:
        metadata:
            labels:
                app: kafka2
        spec:
            containers:
                - name: kafka2
                  image: wurstmeister/kafka
                  ports:
                      - containerPort: 9093
                  env:
                      - name: KAFKA_ZOOKEEPER_CONNECT
                        value: zookeeper:2181/kafka
                      - name: KAFKA_BROKER_ID
                        value: "1"
                      - name: KAFKA_LISTENERS
                        value: PLAINTEXT://:9093
                      - name: KAFKA_ADVERTISED_HOST_NAME
                        value: kafka2
