apiVersion: v1
kind: Service
metadata:
    name: usernet
    # annotations:
    #     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xx-xxxx-x:xxxxxxxxx:xxxxxxx/xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx #replace this value
    #     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
    selector:
        app: userservice
    ports:
        - port: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: userservice
spec:
    selector:
        matchLabels:
            app: userservice
    replicas: 2
    template:
        metadata:
            labels:
                app: userservice
        spec:
            containers:
                - name: userservice
                  image: gcr.io/event-driven-example/userservice:1.0.0
                  env:
                      - name: PORT
                        value: "8002"
                  ports:
                      - containerPort: 8002
