apiVersion: v1
kind: Service
metadata:
  name: userdb
spec:
  selector:
    app: userdb
  ports:
    - port: 3306
      name: db
---
apiVersion: v1
kind: Service
metadata:
  name: userdb-ext
spec:
  selector:
    app: userdb
  ports:
    - port: 3306
      nodePort: 30003
      name: db
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  selector:
    app: adminer
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
      name: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb
spec:
  selector:
    matchLabels:
      app: userdb
  template:
    metadata:
      labels:
        app: userdb
    spec:
      containers:
        - name: userdb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: test
          ports:
            - containerPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080
