apiVersion: v1
kind: Service
metadata:
  name: usernet
  # annotations:
  #     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xx-xxxx-x:xxxxxxxxx:xxxxxxx/xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx #replace this value
  #     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  selector:
    app: userservice
  ports:
    - port: 7000
      nodePort: 30002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  selector:
    matchLabels:
      app: userservice
  replicas: 1
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          # image: gcr.io/event-driven-example/userservice:latest
          image: userservice
          imagePullPolicy: Never
          env:
            - name: LOG4J_ROOTLOGGER
              value: DEBUG, A1
          ports:
            - containerPort: 7000
