apiVersion: v1
kind: Service
metadata:
  name: balancesvc
spec:
  selector:
    app: balanceservice
  ports:
    - port: 5000
      nodePort: 30005
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balanceservice
spec:
  selector:
    matchLabels:
      app: balanceservice
  replicas: 2
  template:
    metadata:
      name: balanceservice
      labels:
        app: balanceservice
    spec:
      containers:
        - name: balanceservice
          image: balanceservice
          # image: gcr.io/event-driven-example/balanceservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
